# Generated by Django 4.2.13 on 2024-05-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
