# Generated by Django 4.2.13 on 2024-06-27 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_options_blogpost_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes_count',
        ),
    ]
