# Generated by Django 4.2.13 on 2024-06-19 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_usertag_blogpost_tagged_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='tagged_users',
        ),
        migrations.AlterField(
            model_name='usertag',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_users', to='blog.blogpost'),
        ),
    ]
