# Generated by Django 4.2.13 on 2024-06-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpost_likes_count_comment_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes_count',
        ),
    ]
